### PR TITLE
fix: check if network is set for chain id before calling readnativedenom

### PR DESCRIPTION
**Pull request by mwmerz**

### CODE REVIEW

**Review by ericHgorski — APPROVED** [review]
Did we want to wrap in useMemo? Otherwise LGTM.

**Comment by mwmerz** [comment]
> Did we want to wrap in useMemo? Otherwise LGTM.

My goal was to get the sprint shipped on friday.  At this point we might as well merge sprint 24 and 25.  Extension and Web's sprint-24 has been perpetually feature creeped to the point where we aren't getting it closed.  The fix here would have at least been able to ship without feature loss between previous sprints.

If you have bandwidth today, please add the useMemo to improve this.

**Comment by ericHgorski** [comment]
> > Did we want to wrap in useMemo? Otherwise LGTM.
> 
> My goal was to get the sprint shipped on friday. At this point we might as well merge sprint 24 and 25. Extension and Web's sprint-24 has been perpetually feature creeped to the point where we aren't getting it closed. The fix here would have at least been able to ship without feature loss between previous sprints.
> 
> If you have bandwidth today, please add the useMemo to improve this.

Implemented.

**Comment by mwmerz** [comment]
> > > Did we want to wrap in useMemo? Otherwise LGTM.
> > 
> > 
> > My goal was to get the sprint shipped on friday. At this point we might as well merge sprint 24 and 25. Extension and Web's sprint-24 has been perpetually feature creeped to the point where we aren't getting it closed. The fix here would have at least been able to ship without feature loss between previous sprints.
> > If you have bandwidth today, please add the useMemo to improve this.
> 
> Implemented.

You're a wizard.  🧙‍♂️ gg

**Pull request merged**
